### ISSUE TITLE
ERRORR typeerror

### ISSUE THREAD

**Issue by Fede-26** [YoungDydlak/web-rpi-fm#4]
[2019-10-21 22:12:22,364] ERROR in app: Exception on /start [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 42, in start
    radio_text = removeNonAscii(file.title)
  File "server.py", line 27, in removeNonAscii
    def removeNonAscii(s): return "".join(i for i in s if ord(i)<128)
TypeError: 'NoneType' object is not iterable

**Comment by Bartekkur1** [comment]
Hi, pasting your console exception here wont tell us much. Could you tell us how to reproduce your error so that we can fix it?

**Comment by Fede-26** [comment]
I select a song from mymusic category, the song doesn't start

**Comment by bmt79** [comment]
I have the same error here, whenever i try and play any music i get the same message in console

**Comment by Bartekkur1** [comment]
have you tried to turn it off and on again?

**Comment by dawiddyd** [comment]
@Fede-26 @BMT79 Try to update Python to the latest version.
